language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: N5uI5hmSu6ffAIl2LIi0GVHWLrnYeJklOhkpxuKj9ebipnTNfbpbH2/0+zRrWHCAj+Gxme2lh9FX0kOGEuSQlY7tRluDXHj3/kPTx7CYplJb4lVQQQgWPzfPMqCUNQtf2mOfS/4q+WusxvqS1k3gU4+WjfyRPKczzsP0U4h/tUrRvKamfJKWcoVdwQ+lpa0wH3FAaRWh1/A95/xmL0JZ5WcUp2O8gQrs8xdkMO2S/ZYC/T9GMgbrhANDkSzLAhtqxW/j2j7AqrlLKDn7RA9zWuWRTOhyplxdKAO1eG3EGVnrCHD0hn8MKfG3Tdzw9wugf8RdB388sovvBlulrqz/CWuHhvEissrpbYV8W7zIPOcMBrEow6XUu9p60LDXW82qohZ11LaoBEXGMfnuoPPkswc1gt5kIn5jJAruCGVJc6UInQRYBBUAuKh0pjf4ukOctwU1/xU66FRV3LfsdHX5NJYvMczZ67mCmAWux0rAewx4gzYZXRlx+/MmhfeFHs5YdpTQxcS3s/Yy2dZ2PC893edsfyIvGrGNKlTPfKeTX9oUOBiQqtMDBH7s9LKs8X3xQWMNded3k/MMkTBqA+xlha5aVkIPVjSioXBlXTiYdpsKEjef7X6no8f5GTDfCZ/P5CBykWOFRRLu/NwxFo7QlvgBv1GWgRRsODiv/bOrxjg=
  app: language-translator-chat
  on:
    repo: RTatineni/language-translator-chat
    

